# Generated by Django 5.1.2 on 2024-11-22 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_remove_gamelevel_level_remove_level_name_and_more'),
        ('users', '0004_userprofile_avatar_userprofile_completed_levels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='current_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.level'),
        ),
    ]
