# Generated by Django 5.1.2 on 2024-10-18 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('correct_answer', models.CharField(max_length=255)),
                ('is_solved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PuzzlePiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='puzzle_pieces/')),
                ('position_x', models.IntegerField()),
                ('position_y', models.IntegerField()),
                ('is_solved', models.BooleanField(default=False)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzle_pieces', to='game.level')),
            ],
        ),
        migrations.CreateModel(
            name='PuzzleQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('level', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='game.level')),
            ],
        ),
        migrations.DeleteModel(
            name='Translation',
        ),
    ]
