# Generated by Django 5.1.2 on 2024-10-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_puzzle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='correct_answer',
            field=models.CharField(max_length=555),
        ),
    ]
