# Generated by Django 5.1.2 on 2024-10-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_level_correct_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='image',
            field=models.ImageField(upload_to='puzzle_pieces/'),
        ),
    ]
