# Generated by Django 5.1.2 on 2024-10-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_puzzle_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
