# Generated by Django 5.1.2 on 2024-10-24 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_puzzle_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.level'),
        ),
        migrations.AlterField(
            model_name='level',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
