# Generated by Django 5.1.2 on 2024-11-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_gamelevel_level_description_alter_game_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='correct_answer',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
