# Generated by Django 5.1.2 on 2024-11-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_alter_level_options_puzzlepiece_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='image_path',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
