# Generated by Django 5.1.2 on 2024-11-21 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_remove_puzzlequestion_level_puzzlequestion_levels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzlequestion',
            name='levels',
        ),
        migrations.AddField(
            model_name='gamelevel',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.level'),
        ),
        migrations.AddField(
            model_name='level',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='puzzlequestion',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='puzzle_question', to='game.level'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.level'),
        ),
        migrations.AlterField(
            model_name='puzzlepiece',
            name='number',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='puzzlequestion',
            name='question_text',
            field=models.CharField(default='What building is this?', max_length=255),
        ),
    ]
