# Generated by Django 5.1.2 on 2024-11-24 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_remove_gamelevel_level_remove_level_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level',
            options={},
        ),
    ]
