# Generated by Django 5.1.2 on 2024-11-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_alter_level_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzlepiece',
            name='image',
            field=models.ImageField(upload_to='puzzle_piece/'),
        ),
    ]
